// ===========================================
// JOURNEY MAPPER - AI TOOL DEFINITIONS
// ===========================================

export const TOOLS_VERSION = {
    version: '3.4.0',
    lastModified: '2026-02-10',
    description: 'Code-First State Machine: Tool scoping, auto-execution, director notes'
};

// Tool Scoping: Define which tools are available at each stage
// This prevents the AI from calling irrelevant tools (e.g., update_cell during IDENTITY)
export const TOOL_SCOPES: Record<string, string[]> = {
    'IDENTITY': ['create_journey_map', 'update_journey_metadata'],
    'PHASES': ['update_journey_metadata', 'set_phases_bulk'],
    'SWIMLANES': ['update_journey_metadata', 'set_swimlanes_bulk', 'generate_matrix'],
    'CELL_POPULATION': ['update_cell', 'update_journey_metadata'],
    'COMPLETE': ['generate_artifacts', 'update_journey_metadata']
};

//
// PROJECT OVERVIEW:
// Journey Mapper is an AI-powered UX research tool that conducts structured interviews
// to create visual journey maps. It combines conversational AI (Gemini) with a live
// interactive canvas that visualizes user experiences as a 2D matrix.
//
// WHAT IS A JOURNEY MAP?
// A journey map is a visual representation of a user's experience over time, organized as:
// - HORIZONTAL AXIS (Phases): Time-based stages (e.g., "Planning", "Execution", "Review")
// - VERTICAL AXIS (Swimlanes): Experience layers (e.g., "Actions", "Thoughts", "Feelings", "Pain Points")
// - CELLS: Intersections of Phase × Swimlane containing specific experiences
//
// Example Journey Map Structure:
// ┌──────────────┬──────────────┬──────────────┬──────────────┐
// │              │ Phase 1      │ Phase 2      │ Phase 3      │
// │              │ "Planning"   │ "Execution"  │ "Review"     │
// ├──────────────┼──────────────┼──────────────┼──────────────┤
// │ Actions      │ Cell: What   │ Cell: What   │ Cell: What   │
// │ (Swimlane 1) │ they DO in   │ they DO in   │ they DO in   │
// │              │ Planning     │ Execution    │ Review       │
// ├──────────────┼──────────────┼──────────────┼──────────────┤
// │ Feelings     │ Cell: How    │ Cell: How    │ Cell: How    │
// │ (Swimlane 2) │ they FEEL in │ they FEEL in │ they FEEL in │
// │              │ Planning     │ Execution    │ Review       │
// └──────────────┴──────────────┴──────────────┴──────────────┘
//
// CANVAS FUNCTIONALITY:
// The frontend renders a live, interactive canvas that updates in real-time as the AI
// populates data via tool calls:
// 1. Journey Header: Displays journey name, description, user identity
// 2. Matrix Grid: Phase columns × Swimlane rows (auto-generated from structure)
// 3. Cell Content: Each cell shows headline + description (captured via interview)
// 4. Artifact Panel: Displays final summary, mental models, quotes (Step 13)
//
// INTERVIEW FLOW (13 Steps):
// 1-2.   Identity: Capture user name/role → create_journey_map
// 3-4.   Journey: Capture journey name/description → update_journey_metadata
// 5-6.   Phases: Define horizontal axis (stages) → set_phases_bulk
// 7-8.   Swimlanes: Define vertical axis (layers) → set_swimlanes_bulk → generate_matrix
// 9.     Matrix: Verify grid exists (auto-generated by set_swimlanes_bulk)
// 10.    Cells: Populate each cell one-by-one → update_cell (repeated N times)
// 11-12. Deep Dive: Ethnographic analysis + final check → update_journey_metadata
// 13.    Artifacts: Generate summary, mental models, quotes → generate_artifacts
//
// SEPARATION OF CONCERNS:
//
// THIS FILE (tools.ts):
// - Defines the 7 AI function calling tools as Gemini FunctionDeclarations
// - Specifies tool names, descriptions, parameters, and required fields
// - Consumed by Gemini model to understand WHAT actions it can take
// - These are the AI's "hands" - the only way it can modify journey state
//
// prompts.ts:
// - Defines the 13-step interview logic as system instructions
// - Controls WHEN and HOW the AI uses tools (the "brain")
// - Handles template configuration (admin pre-fills) via code-first state machine
// - Builds dynamic instructions based on session config + journey state
//
// server.ts:
// - Handles HTTP/SSE streaming for /api/chat endpoint
// - Executes tool calls by invoking store.ts methods
// - Refreshes journey state after each tool call
// - Rebuilds AI model with updated system instruction
//
// store.ts:
// - Manages journey state in Firestore (database layer)
// - Implements the 7 tool methods (create, update, set phases/swimlanes, update cell, generate artifacts)
// - Enforces stage transitions (IDENTITY → PHASES → SWIMLANES → CELL_POPULATION → COMPLETE)
// - Calculates completion status, cell grid, metrics
//
// API STRUCTURE:
//
// Frontend → Backend:
// - POST /api/chat
//   Body: { message, sessionConfig?, journeyId? }
//   Response: SSE stream (text chunks + tool execution events)
//
// - GET /api/journey-state/:journeyId
//   Response: { journeyId, name, description, stage, phases[], swimlanes[], cells[], completionStatus, metrics }
//
// Backend → Firestore:
// - Collection: journey_maps
//   Document ID: UUID
//   Fields: { journeyId, name, userName, role, description, stage, status, phases[], swimlanes[], cells[], context, artifacts, createdAt, updatedAt }
//
// ADMIN CAPABILITIES:
//
// Admins can create templates via /admin UI that pre-populate interview fields:
// - Identity: name, role (skip asking if provided)
// - Journey: journeyName, journeyDescription, journeyPrompt (custom question)
// - Structure: phases[], swimlanes[] (with or without descriptions)
// - Persona: welcomePrompt, personaFrame, personaLanguage, agentName
// - Knowledge: ragContext (knowledge base for synthesis)
//
// Templates are stored in Firestore (admin_links collection) and loaded via URL: /?id=<templateId>
//
// ADMIN PRE-FILL BEHAVIOR (Silent Configuration Pattern):
// - When admin provides FULL data (e.g., phases with descriptions):
//   → AI sees ONLY "Call tool immediately with this data" instruction
//   → Skips asking user entirely (deterministic bypass)
// - When admin provides PARTIAL data (e.g., phase names, no descriptions):
//   → AI sees "Probe for missing descriptions, then call tool" instruction
//   → Asks user only for missing data
// - When admin provides NO data:
//   → AI sees full interview logic (ask, confirm, probe, save)
//
// This approach ensures admin pre-fills are enforced by TypeScript code, not AI "understanding".
// The AI cannot override admin decisions because alternative instructions are deleted from the prompt.
//
// ===========================================
// TOOL DEFINITIONS
// ===========================================

export const JOURNEY_TOOLS = [
    {
        functionDeclarations: [
            {
                name: "create_journey_map",
                description: "Initialize a new journey map when the user provides their name and role.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        name: { type: "STRING", description: "Name of the journey/project (e.g. 'Draft')" },
                        userName: { type: "STRING", description: "The User's Name" },
                        role: { type: "STRING", description: "User's role" },
                        description: { type: "STRING", description: "Any extra context provided" }
                    },
                    required: ["name", "userName", "role"]
                }
            },
            {
                name: "update_journey_metadata",
                description: "Update the journey name and description after the user explains the process.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        journeyMapId: { type: "STRING" },
                        name: { type: "STRING", description: "Succinct journey name" },
                        description: { type: "STRING", description: "Detailed description/context" }
                    },
                    required: ["journeyMapId", "name"]
                }
            },
            {
                name: "set_phases_bulk",
                description: "Set the list of high-level phases (steps) for the journey. Description is optional - backend will handle empty descriptions.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        journeyMapId: { type: "STRING" },
                        phases: {
                            type: "ARRAY",
                            items: {
                                type: "OBJECT",
                                properties: {
                                    name: { type: "STRING" },
                                    description: { type: "STRING" }
                                },
                                required: ["name"]  // ← Description now optional
                            }
                        }
                    },
                    required: ["journeyMapId", "phases"]
                }
            },
            {
                name: "set_swimlanes_bulk",
                description: "Set the list of actors/swimlanes. Description is optional - backend will handle empty descriptions. IMPORTANT: This automatically triggers matrix generation internally. DO NOT call generate_matrix after this tool.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        journeyMapId: { type: "STRING" },
                        swimlanes: {
                            type: "ARRAY",
                            items: {
                                type: "OBJECT",
                                properties: {
                                    name: { type: "STRING" },
                                    description: { type: "STRING" }
                                },
                                required: ["name"]  // ← Description now optional
                            }
                        }
                    },
                    required: ["journeyMapId", "swimlanes"]
                }
            },
            {
                name: "generate_matrix",
                description: "Generate the empty cell grid. Call this immediately after setting phases and swimlanes.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        journeyMapId: { type: "STRING" }
                    },
                    required: ["journeyMapId"]
                }
            },
            {
                name: "update_cell",
                description: "Save content for a specific cell intersection. You MUST identify the cell by its cellId (UUID) from the journeyState.cells array.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        journeyMapId: { type: "STRING" },
                        cellId: { type: "STRING", description: "The UUID of the cell from journeyState.cells (REQUIRED)" },
                        headline: { type: "STRING", description: "Succinct title/headline for the intersection (e.g. 'Data Entry')" },
                        description: { type: "STRING", description: "Detailed description of what happens based ONLY on user input. Do not Hallucinate." },
                        context: { type: "STRING", description: "Any extra spillover notes or raw details." }
                    },
                    required: ["journeyMapId", "cellId", "headline", "description"]
                }
            },
            {
                name: "generate_artifacts",
                description: "Finalize the journey. You MUST provide 'summaryOfFindings' and 'mentalModels' based on the conversation.",
                parameters: {
                    type: "OBJECT",
                    properties: {
                        journeyMapId: { type: "STRING" },
                        summaryOfFindings: { type: "STRING", description: "Comprehensive summary of findings" },
                        mentalModels: { type: "STRING", description: "Identified mental models" },
                        quotes: { 
                            type: "ARRAY", 
                            description: "2-5 most interesting verbatim direct quotes from the participant's chat messages",
                            items: { type: "STRING" }
                        },
                        anythingElse: { type: "STRING", description: "Any final additions from the user" }
                    },
                    required: ["journeyMapId", "summaryOfFindings", "mentalModels", "quotes"]
                }
            }
        ]
    }
];
